### CMQT Blood Pressure QC

This document performs quality control checks on the cmqt_blood_pressure data sets. Specific checks are determined through a collaborative effort between the CMQT sub-working group, the Phenotype Harmonization Working Group, and the CC. 

```{r}
# check file_name and df passed in 

# head(df)
# print(file_name)
```

```{r}
# Set min and max limits for QC check 

vars <- c('systolic_bp_1', 'diastolic_bp_1')

# biologically implausible values for blood pressure
# min_values <- c(70, 50)
# max_values <- c(270, 150)

# min and max values that are mean +/- 4 SD outlier detection
min_values <- apply(df[vars], 2, mean, na.rm=TRUE) - 4*apply(df[vars], 2, sd, na.rm=TRUE)
max_values <- apply(df[vars], 2, mean, na.rm=TRUE) + 4*apply(df[vars], 2, sd, na.rm=TRUE)

vars_df <- data.frame(vars)
vars_df$min_values <- min_values
vars_df$max_values <- max_values
vars_df$qc_pass <- c(rep(-1, length(vars)))
vars_df$qc_fail_min <- c(rep(-1, length(vars)))
vars_df$qc_fail_max <- c(rep(-1, length(vars)))
vars_df$qc_null <- c(rep(-1, length(vars)))
```

```{r}
# Check for extreme values in dataset

this_table <- as.data.frame(df) 

for (i in 1:length(vars)) {
  var_name = vars[i]
  
  this_variable <- eval(parse(text=paste0("this_table$", var_name)))
  
  max <- vars_df[i, 3]
  min <- vars_df[i, 2]
  
  vars_df[c(i),]$qc_pass <- c(sum(this_variable <= max & this_variable >= min))
  vars_df[c(i),]$qc_fail_min <- c(sum(this_variable < min))
  vars_df[c(i),]$qc_fail_max <- c(sum(this_variable > max))
  vars_df[c(i),]$qc_null <- c(sum(is.null(this_variable)))
}

# Check for systolic blood pressure < diastolic blood pressure 

vars_df <- vars_df %>% add_row(
  vars = 'bp_consistency', 
  min_values = NULL, 
  max_values = NULL, 
  qc_pass = sum(this_table$systolic_bp_1 > this_table$diastolic_bp_1), 
  qc_fail_min = sum(this_table$systolic_bp_1 <= this_table$diastolic_bp_1), 
  qc_fail_max = NULL, 
  qc_null = c(sum(is.na(this_table$systolic_bp_1) | is.na(this_table$diastolic_bp_1)))
)

kable(vars_df, col.names = c('Variable', 'Min Value', 'Max Value', 'Pass QC', 'Fail QC Min', 'Fail QC Max', 'Null Values'),  caption = "QC check for blood pressure variables")
```