### CMQT Hematology QC 

This document performs quality control checks on the cmqt_hematology data sets. Specific checks are determined through a collaborative effort between the CMQT sub-working group, the Phenotype Harmonization Working Group, and the CC. 

```{r}
# Read in data

df <- read.table(file = '/home/rstudio/primed-file-checks/pheno_qc/test_data/cmqt_hematology.tsv', sep = '\t', header = TRUE)
```

```{r}
# Set min and max limits for QC check 

vars <- c('wbc_1', 'hemoglobin_1', 'hematocrit_1', 'platelet_count_1')

# biologically implausible values for blood pressure
# min_values <- c(0, 0, 0, 0) 
# max_values <- c(200, 20, 60, 1000)

# min and max values that are mean +/- 4 SD outlier detection
min_values <- sapply(df[vars], mean) - 4*sapply(df[vars], sd)
max_values <- sapply(df[vars], mean) + 4*sapply(df[vars], sd)

vars_df <- data.frame(vars)
vars_df$min_values <- min_values
vars_df$max_values <- max_values
vars_df$qc_pass <- c(rep(-1, length(vars)))
vars_df$qc_fail_min <- c(rep(-1, length(vars)))
vars_df$qc_fail_max <- c(rep(-1, length(vars)))
vars_df$qc_null <- c(rep(-1, length(vars)))
```

```{r}
# Check for extreme values in dataset

this_table <- as.data.frame(df)

for (i in 1:length(vars)) {
  var_name = vars[i]
  
  this_variable <- eval(parse(text=paste0("this_table$", var_name)))
  
  max <- vars_df[i, 3]
  min <- vars_df[i, 2]
  
  vars_df[c(i),]$qc_pass <- c(sum(this_variable <= max & this_variable >= min))
  vars_df[c(i),]$qc_fail_min <- c(sum(this_variable < min))
  vars_df[c(i),]$qc_fail_max <- c(sum(this_variable > max))
  vars_df[c(i),]$qc_null <- c(sum(sapply(this_variable,is.null)))
}

kable(vars_df, col.names = c('Variable', 'Min Value', 'Max Value', 'Pass QC', 'Fail QC Min', 'Fail QC Max', 'Null Values'),  caption = "QC check for hematology variables")
```
