---
title: "template_main_qc"
author: "Alyna Khan"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  html_document:
    toc: true
params: 
  tables: ""
  path: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(knitr)
library(ggplot2)
```

# Main Document 

```{r}
# parameters <- list(tables=table_files, path=filepath)
# table_files is a two column tsv file with (table_names, file_names)


child_document <- "template_general_qc.Rmd" # the child doc will be the general qc Rmd

grandchild_document_table_names <- params$tables$table_names
grandchild_document_file_names <- params$tables$file_names
```

```{r, results='asis'}
# Call child document for general QC check 
# This chunk will loop through the list of table names to be QC'd 

res <- vector(mode = "list", length = length(grandchild_document_table_names))

for (i in 1:length(grandchild_document_table_names)) {
  grandchild_document_table_name <- paste0(grandchild_document_table_names[i], "_qc")
  grandchild_document_file_name <- grandchild_document_file_names[i]
  print("running general qc for")
  print(grandchild_document_table_name)
  print(grandchild_document_file_name)
  res[[i]] <- knitr::knit_child(child_document, quiet = TRUE, envir = environment())
}

cat(unlist(res), sep = '\n')
```