`r paste("## QC Checks for ", grandchild_document_table_name)`

This section has QC checks for the `r grandchild_document_table_name` table. 

```{r}
# Read in data

file_name <- grandchild_document_file_name

df <- read_table(file_name,
                 col_types = cols(subject_id="c"),
                 guess_max=100000,
                 show_col_types=TRUE)



# for testing locally 

# file_name <- 'gs://fc-secure-0285a1eb-c88a-4ea6-b970-ec5e092784ea/uploaded_data_prevent/aric_cmqt_blood_pressure.tsv'
# file_name <- as.character(grandchild_document_file_name)
# table_pipe <- gsutil_pipe(file_name, "rb")
# df <- read_table(table_pipe)
```

```{r}
# Separate variable into binary, categorical, and continuous 

categorical_vars <- c()
binary_vars <- c()
continuous_vars <- c()

for(i in 1:length(df)){
  if(typeof(df[[i]]) == "character") {
    # if column type is character, variable is categorical 
    categorical_vars <- c(categorical_vars, colnames(df[i]))
  } else if(typeof(df[[i]]) == "double") {
    if(all(sapply(df[i], function(x) x %in% c(0, 1, NA)))) { 
      # if column type is double and has only 0,1 values, it is binary 
      binary_vars <- c(binary_vars, colnames(df[i]))
    } else {
      # if column type is double and has more than just 0,1 values, it is continuous  
      continuous_vars <- c(continuous_vars, colnames(df[i]))
    }
  }
}
```


```{r}
# Age specific check 

vars <- c('age_at_obs')

# Summary statistics 
min <- apply(df[vars], 2, min, na.rm=TRUE)
max <- apply(df[vars], 2, max, na.rm=TRUE)
mean <- apply(df[vars], 2, mean, na.rm=TRUE)
med <- apply(df[vars], 2, median, na.rm=TRUE)

# QC min and max values that are outside acceptable range
qc_min <- c(0)
qc_max <- c(90)

age_df <- data.frame(vars)
age_df$min <- round(min, 2)
age_df$max <- round(max, 2)
age_df$mean <- round(mean, 2)
age_df$median <- round(med, 2)
age_df$qc_min <- round(qc_min, 2) 
age_df$qc_max <- round(qc_max, 2)
age_df$qc_pass <- c(rep(-1, length(vars)))
age_df$qc_fail_min <- c(rep(-1, length(vars)))
age_df$qc_fail_max <- c(rep(-1, length(vars)))
age_df$qc_null <- c(rep(-1, length(vars)))
```

```{r}
# Check for extreme values in age

for (i in 1:length(vars)) {
  var_name = vars[i]
  
  this_variable <- eval(parse(text=paste0("df$", var_name)))
  
  max <- age_df[i, 3]
  min <- age_df[i, 2]
  
  age_df[c(i),]$qc_pass <- c(sum(this_variable <= max & this_variable >= min))
  age_df[c(i),]$qc_fail_min <- c(sum(this_variable < min))
  age_df[c(i),]$qc_fail_max <- c(sum(this_variable > max))
  age_df[c(i),]$qc_null <- c(sum(is.null(this_variable)))
}
```

```{r}
# General checks for all continuous variables in table 

continuous_vars <- continuous_vars[continuous_vars != "subject_id"]
vars <- continuous_vars[continuous_vars != "subject_id" & continuous_vars != "age_at_obs"]

# Summary statistics 
min <- apply(df[vars], 2, min, na.rm=TRUE)
max <- apply(df[vars], 2, max, na.rm=TRUE)
mean <- apply(df[vars], 2, mean, na.rm=TRUE)
med <- apply(df[vars], 2, median, na.rm=TRUE)


# QC min and max values that are mean +/- 4 SD outlier detection
qc_min <- apply(df[vars], 2, mean, na.rm=TRUE) - 4*apply(df[vars], 2, sd, na.rm=TRUE)
qc_max <- apply(df[vars], 2, mean, na.rm=TRUE) + 4*apply(df[vars], 2, sd, na.rm=TRUE)

vars_df <- data.frame(vars)
vars_df$min <- round(min, 2)
vars_df$max <- round(max, 2)
vars_df$mean <- round(mean, 2)
vars_df$median <- round(med, 2)
vars_df$qc_min <- round(qc_min, 2) 
vars_df$qc_max <- round(qc_max, 2)
vars_df$qc_pass <- c(rep(-1, length(vars)))
vars_df$qc_fail_min <- c(rep(-1, length(vars)))
vars_df$qc_fail_max <- c(rep(-1, length(vars)))
vars_df$qc_null <- c(rep(-1, length(vars)))
```

```{r}
# Check for extreme values in all continuous variables 

for (i in 1:length(vars)) {
  var_name = vars[i]
  
  this_variable <- eval(parse(text=paste0("df$", var_name)))
  
  max <- vars_df[i, 7]
  min <- vars_df[i, 6]
  
  vars_df[c(i),]$qc_pass <- c(sum(this_variable <= max & this_variable >= min, na.rm=TRUE))
  vars_df[c(i),]$qc_fail_min <- c(sum(this_variable < min, na.rm=TRUE))
  vars_df[c(i),]$qc_fail_max <- c(sum(this_variable > max, na.rm=TRUE))
  vars_df[c(i),]$qc_null <- c(sum(is.na(this_variable)))
}
```

Continuous Variables: 

- age: 
  - QC Min: 0
  - QC Max: 90
- `r continuous_vars`:
  - QC Min: -4SD outlier
  - QC Min: +4SD outlier
  
```{r}
kable(rbind(age_df, vars_df), col.names = c('Variable', 'Min Value', 'Max Value', "Mean", "Median", "QC Min", "QC Max", 'Pass QC', 'Fail QC Min', 'Fail QC Max', 'Null Values'))
```

```{r}
# Histogram of continuous variables 
for(var in continuous_vars) {
  print (
    ggplot(aes_string(x=var), data=df) +
      geom_histogram(bins=30) +
      xlab(var)
  )
}
```

Binary Variables: `r binary_vars`

Categorical Variables: `r categorical_vars`

```{r, results='asis'}
# Bar charts of binary and categorical variable with table
for(var in c(binary_vars, categorical_vars)) {
  print ( 
    ggplot(aes_string(x=var), data=df) +
      geom_bar() +
      xlab(var)
  ) 
  
  this_table <- df %>% group_by (
      .data[[var]] 
      ) %>% summarise(
        count = n()
      )
  print(kable(this_table, col.names = c(var, "count")))
}
```

Number of unique measurements for each person: 

```{r}
# Table with number of timepoints and participants for each variable 

this_table <- df %>% group_by(
  subject_id
) %>% summarise(
  count = n()
) %>% ungroup(
) %>% group_by(
  num_timepoints = count
) %>% summarise(
  num_participants = n()
)

kable(this_table)
```

```{r}
# Complete constructing the file name for current table to be QC'd with table-specific checks

grandchild_document <- paste0(grandchild_document_table_name, "_qc.Rmd") 
```

```{r}
knitr::asis_output(knitr::knit_child(grandchild_document, quiet=TRUE))
# knitr::knit_child(grandchild_document, quiet = TRUE)
```