version: 1.2
workflows:
   - name: data_model_report
     subclass: WDL
     primaryDescriptorPath: /data_model_report.wdl
     testParameterFiles:
         - /data_model_report.json
   - name: genotype_report
     subclass: WDL
     primaryDescriptorPath: /genotype_report.wdl
     testParameterFiles:
         - /genotype_report.json
   - name: gsr_report
     subclass: WDL
     primaryDescriptorPath: /gsr_report.wdl
     testParameterFiles:
         - /gsr_report.json
   - name: gsr_report
     subclass: WDL
     primaryDescriptorPath: /gsr_data_report.wdl
     testParameterFiles:
         - /gsr_data_report.json
   - name: data_dictionary_report
     subclass: WDL
     primaryDescriptorPath: /data_dictionary_report.wdl
     testParameterFiles:
         - /data_dictionary_report.json
   - name: data_table_import
     subclass: WDL
     primaryDescriptorPath: /data_table_import.wdl
     testParameterFiles:
         - /data_table_import.json
