version: 1.2
workflows:
   - name: validate_phenotype_model
     subclass: WDL
     primaryDescriptorPath: /validate_phenotype_model.wdl
     testParameterFiles:
         - /validate_phenotype_model.json
   - name: validate_genotype_model
     subclass: WDL
     primaryDescriptorPath: /validate_genotype_model.wdl
     testParameterFiles:
         - /validate_genotype_model.json
   - name: validate_gsr_model
     subclass: WDL
     primaryDescriptorPath: /validate_gsr_model.wdl
     testParameterFiles:
         - /validate_gsr_model.json
   - name: gsr_data_report
     subclass: WDL
     primaryDescriptorPath: /gsr_data_report.wdl
     testParameterFiles:
         - /gsr_data_report.json
   - name: check_vcf_samples
     subclass: WDL
     primaryDescriptorPath: /check_vcf_samples.wdl
     testParameterFiles:
         - /check_vcf_samples.json
  - name: pheno_qc
     subclass: WDL
     primaryDescriptorPath: /pheno_qc/pheno_qc.wdl
     testParameterFiles:
         - /pheno_qc/pheno_qc.json


