name: Womtool

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "main" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:

  detect-wdl-files:
    runs-on: ubuntu-latest
    name: "Detect WDL files"
    outputs:
        matrix: ${{ steps.detect-wdl-files.outputs.wdl-file }}

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Detect WDL files
        id: detect-wdl-files
        run: |
          echo "::set-output name=wdl-file::$(find . -name '*.wdl' -type f -print0 | xargs -0)"

      - name: Show WDL files
        run: echo "${{ steps.detect-wdl-files.outputs.wdl-file }}"

  run-womtool:
    needs: detect-wdl-files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.detect-wdl-files.outputs.matrix) }}

    name: "Run womtool: ${{ matrix.wdl-file }}"

    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Run womtool
        uses: UW-GAC/womtool-action@main
        with:
            wdl-file: ${{ matrix.wdl-file }}
